server:
  port: 8030
  servlet:
    context-path: /

spring:
  application:
    name: user-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbwlwq?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&userSSL=false
    username: root
    password: root
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dbwlwq?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
#    username: root
#    password: root

  cloud:
    nacos:
      server-addr: 192.168.3.3:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP

  redis: # redis配置
    host: 192.168.3.3 # IP
    port: 6379  # 端口
    password:  # 密码
    connect-timeout: 20s  # 连接超时时间
    lettuce: # lettuce redis客户端配置
      pool: # 连接池配置
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 200s  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

