#server:
#  port: 8088
spring:
#  application:
#    name: gateway-server
  cloud:
#    nacos:
#      server-addr: 192.168.3.3:8848
#      discovery:
#        username: nacos
#        password: nacos
#        namespace: public
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer-servi/**
          filters:
            - StripPrefix=1
        - id: server-service
          uri: lb://server-service
          predicates:
            - Path=/server-servi/**
          filters:
            - StripPrefix=1